"""
Setup script for NIDS Autoencoder
Run this once to set up your project structure
"""

import os
from pathlib import Path
import shutil

def setup_nids_autoencoder():
    """
    Create necessary directories and verify structure
    """
    print("="*70)
    print("NIDS AUTOENCODER - PROJECT SETUP")
    print("="*70)
    
    # Get project root (where this script is located)
    project_root = Path(__file__).parent
    print(f"\nProject Root: {project_root}")
    
    # Define required directories
    directories = {
        'src': project_root / 'src',
        'models': project_root / 'models',
        'data_raw': project_root / 'data' / 'raw',
        'data_processed': project_root / 'data' / 'processed',
        'result': project_root / 'result',
        'reports': project_root / 'reports'
    }
    
    # Create directories if they don't exist
    print("\n1. Creating/Verifying Directories:")
    print("-" * 70)
    
    for name, path in directories.items():
        if path.exists():
            print(f"  ✅ {name:15} : {path} (exists)")
        else:
            path.mkdir(parents=True, exist_ok=True)
            print(f"  ✨ {name:15} : {path} (created)")
    
    # Check for Python files
    print("\n2. Checking Python Files:")
    print("-" * 70)
    
    required_files = {
        'autoencoder_nids.py': 'Core autoencoder module',
        'optimized_autoencoder_config.py': 'Memory-optimized version',
        'autoencoder_integration.py': 'GUI integration layer',
        'train_autoencoder.py': 'Training script'
    }
    
    src_dir = directories['src']
    all_present = True
    
    for filename, description in required_files.items():
        filepath = src_dir / filename
        if filepath.exists():
            size_kb = filepath.stat().st_size / 1024
            print(f"  ✅ {filename:35} : {size_kb:.1f} KB - {description}")
        else:
            print(f"  ❌ {filename:35} : MISSING - {description}")
            all_present = False
    
    # Check main.py
    print("\n3. Checking Main Application:")
    print("-" * 70)
    
    main_py = project_root / 'main.py'
    if main_py.exists():
        print(f"  ✅ main.py found : {main_py}")
    else:
        print(f"  ⚠️  main.py not found in project root")
    
    # Check data files
    print("\n4. Checking Data Files:")
    print("-" * 70)
    
    data_raw_dir = directories['data_raw']
    csv_files = list(data_raw_dir.glob('*.csv'))
    
    if csv_files:
        print(f"  ✅ Found {len(csv_files)} CSV file(s):")
        for csv_file in csv_files[:5]:  # Show first 5
            size_mb = csv_file.stat().st_size / (1024**2)
            print(f"     - {csv_file.name} ({size_mb:.2f} MB)")
        if len(csv_files) > 5:
            print(f"     ... and {len(csv_files) - 5} more")
    else:
        print(f"  ⚠️  No CSV files found in data/raw/")
        print(f"     Place your NetFlow data files in: {data_raw_dir}")
    
    # Create README for each directory
    print("\n5. Creating Directory README Files:")
    print("-" * 70)
    
    readmes = {
        'models': "# Models Directory\n\nTrained autoencoder models are saved here.\n\nFiles:\n- autoencoder_nids.pth : Full trained model\n- autoencoder_best.pth : Best model during training\n- autoencoder_features.json : Feature metadata\n",
        
        'data_raw': "# Raw Data Directory\n\nPlace your original NetFlow CSV files here.\n\nExpected format:\n- CSV files with NetFlow features\n- Must include 'label' column for supervised training\n- Common columns: duration, protocol, src_port, dst_port, etc.\n",
        
        'result': "# Results Directory\n\nTraining plots and analysis results are saved here.\n\nGenerated files:\n- autoencoder_training_history.png\n- autoencoder_confusion_matrix.png\n- autoencoder_error_distribution.png\n- autoencoder_predictions.csv\n",
        
        'reports': "# Reports Directory\n\nPDF reports generated by the GUI are saved here.\n"
    }
    
    for dir_name, content in readmes.items():
        if dir_name in ['models', 'data_raw', 'result', 'reports']:
            readme_path = directories[dir_name] / 'README.md'
            if not readme_path.exists():
                readme_path.write_text(content)
                print(f"  ✨ Created README in {dir_name}/")
    
    # Create .gitignore
    print("\n6. Creating .gitignore:")
    print("-" * 70)
    
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
nids_env/
venv/
ENV/

# Models (too large for git)
models/*.pth
models/*.pkl

# Data (too large for git)
data/raw/*.csv
data/processed/*.csv

# Results
result/*.png
result/*.csv

# Reports
reports/*.pdf

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""
    
    gitignore_path = project_root / '.gitignore'
    if not gitignore_path.exists():
        gitignore_path.write_text(gitignore_content)
        print("  ✨ Created .gitignore")
    else:
        print("  ✅ .gitignore already exists")
    
    # Summary
    print("\n" + "="*70)
    print("SETUP SUMMARY")
    print("="*70)
    
    if all_present and csv_files:
        print("✅ Setup Complete! You're ready to train the autoencoder.")
        print("\nNext Steps:")
        print("1. Activate your virtual environment:")
        print("   nids_env\\Scripts\\activate")
        print("\n2. Train the autoencoder:")
        print("   python src/train_autoencoder.py --data data/raw/your_data.csv")
        print("\n3. Or use optimized version:")
        print("   python src/optimized_autoencoder_config.py")
    else:
        print("⚠️  Setup Incomplete - Action Required:")
        if not all_present:
            print("\n❌ Missing Python files:")
            print("   Please save the 4 autoencoder Python files in src/ directory")
        if not csv_files:
            print("\n❌ Missing data files:")
            print("   Please place your NetFlow CSV files in data/raw/ directory")
    
    print("\n" + "="*70)
    
    # Create quick reference
    quick_ref = """# NIDS Autoencoder - Quick Reference

## File Locations
- **Python Files**: `src/`
- **Models**: `models/`
- **Data**: `data/raw/`
- **Results**: `result/`

## Training Commands

### Option 1: Auto-optimized (Recommended)
```bash
python src/optimized_autoencoder_config.py
```

### Option 2: Manual training
```bash
python src/train_autoencoder.py --data data/raw/your_data.csv --epochs 30 --batch-size 128
```

### Option 3: From Python
```python
import sys
sys.path.append('src')
from optimized_autoencoder_config import train_optimized

train_optimized('data/raw/your_data.csv')
```

## GUI Integration

In your main.py:
```python
import sys
sys.path.append('src')
from autoencoder_integration import AutoencoderIntegration

# Initialize
ae = AutoencoderIntegration('models/autoencoder_nids.pth')

# Analyze packet
result = ae.analyze_packet_for_gui(packet_data)
```

## Troubleshooting
- High RAM usage? Reduce batch size: `--batch-size 64`
- Training slow? Reduce epochs: `--epochs 15`
- Out of memory? Limit samples in optimized_autoencoder_config.py
"""
    
    quick_ref_path = project_root / 'AUTOENCODER_README.md'
    quick_ref_path.write_text(quick_ref)
    print(f"\n📝 Quick reference saved to: {quick_ref_path}")


if __name__ == "__main__":
    setup_nids_autoencoder()
    
    print("\n" + "="*70)
    print("Press Enter to exit...")
    input()
